services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - "/Applications/XAMPP/xamppfiles/htdocs/project/form-builder:/var/www/html"
    depends_on:
      - postgres
    networks:
      - laravel_network
    build:
      context: .
      dockerfile: Dockerfile

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - "/Applications/XAMPP/xamppfiles/htdocs/project/form-builder:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app
    networks:
      - laravel_network

  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  pgdata:
